# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

LOCAL_PATH := vendor/lenovo/x103f

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/usr/keylayout/FT5x36.kl:system/usr/keylayout/FT5x36.kl \
    $(LOCAL_PATH)/proprietary/usr/keylayout/synaptics_dsx.kl:system/usr/keylayout/synaptics_dsx.kl \
    $(LOCAL_PATH)/proprietary/usr/keylayout/ft5x06_ts.kl:system/usr/keylayout/ft5x06_ts.kl \
    $(LOCAL_PATH)/proprietary/usr/keylayout/Goodix-TS.kl:system/usr/keylayout/Goodix-TS.kl \
    $(LOCAL_PATH)/proprietary/usr/keylayout/gpio-keys.kl:system/usr/keylayout/gpio-keys.kl \
    $(LOCAL_PATH)/proprietary/usr/keylayout/atmel_mxt_ts.kl:system/usr/keylayout/atmel_mxt_ts.kl \
    $(LOCAL_PATH)/proprietary/lib/sensors.native.so:system/lib/sensors.native.so \
    $(LOCAL_PATH)/proprietary/lib/hw/camera.msm8909.so:system/lib/hw/camera.msm8909.so \
    $(LOCAL_PATH)/proprietary/lib/hw/sensors.msm8909.so:system/lib/hw/sensors.msm8909.so \
    $(LOCAL_PATH)/proprietary/lib/hw/lights.msm8909.so:system/lib/hw/lights.msm8909.so \
    $(LOCAL_PATH)/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so \
    $(LOCAL_PATH)/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    $(LOCAL_PATH)/proprietary/lib/libtsvideoprocess.so:system/lib/libtsvideoprocess.so \
    $(LOCAL_PATH)/proprietary/lib/modules/pronto/pronto_wlan.ko:system/lib/modules/pronto/pronto_wlan.ko \
    $(LOCAL_PATH)/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    $(LOCAL_PATH)/proprietary/etc/init.qcom.debug.sh:system/etc/init.qcom.debug.sh \
    $(LOCAL_PATH)/proprietary/etc/init.qcom.uicc.sh:system/etc/init.qcom.uicc.sh \
    $(LOCAL_PATH)/proprietary/etc/init.qcom.post_boot.sh:system/etc/init.qcom.post_boot.sh \
    $(LOCAL_PATH)/proprietary/etc/init.qcom.audio.sh:system/etc/init.qcom.audio.sh \
    $(LOCAL_PATH)/proprietary/etc/init.qcom.modem_links.sh:system/etc/init.qcom.modem_links.sh \
    $(LOCAL_PATH)/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    $(LOCAL_PATH)/proprietary/etc/wifi/p2p_supplicant_overlay.conf:system/etc/wifi/p2p_supplicant_overlay.conf \
    $(LOCAL_PATH)/proprietary/etc/wifi/WCNSS_qcom_cfg.ini:system/etc/wifi/WCNSS_qcom_cfg.ini \
    $(LOCAL_PATH)/proprietary/etc/wifi/wpa_supplicant_overlay.conf:system/etc/wifi/wpa_supplicant_overlay.conf \
    $(LOCAL_PATH)/proprietary/etc/firmware/wlan/prima/WCNSS_cfg.dat:system/etc/firmware/wlan/prima/WCNSS_cfg.dat \
    $(LOCAL_PATH)/proprietary/etc/firmware/venus.b02:system/etc/firmware/venus.b02 \
    $(LOCAL_PATH)/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/widevine.mdt:system/etc/firmware/widevine.mdt \
    $(LOCAL_PATH)/proprietary/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/venus.b00:system/etc/firmware/venus.b00 \
    $(LOCAL_PATH)/proprietary/etc/firmware/venus.mdt:system/etc/firmware/venus.mdt \
    $(LOCAL_PATH)/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/widevine.b02:system/etc/firmware/widevine.b02 \
    $(LOCAL_PATH)/proprietary/etc/firmware/widevine.b01:system/etc/firmware/widevine.b01 \
    $(LOCAL_PATH)/proprietary/etc/firmware/venus.b01:system/etc/firmware/venus.b01 \
    $(LOCAL_PATH)/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/widevine.b00:system/etc/firmware/widevine.b00 \
    $(LOCAL_PATH)/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/venus.mbn:system/etc/firmware/venus.mbn \
    $(LOCAL_PATH)/proprietary/etc/firmware/widevine.b03:system/etc/firmware/widevine.b03 \
    $(LOCAL_PATH)/proprietary/etc/firmware/venus.b03:system/etc/firmware/venus.b03 \
    $(LOCAL_PATH)/proprietary/etc/firmware/venus.b04:system/etc/firmware/venus.b04 \
    $(LOCAL_PATH)/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    $(LOCAL_PATH)/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    $(LOCAL_PATH)/proprietary/etc/init.qcom.bt.sh:system/etc/init.qcom.bt.sh \
    $(LOCAL_PATH)/proprietary/etc/init.qcom.wifi.sh:system/etc/init.qcom.wifi.sh \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:system/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/QRD_Headset_cal.acdb:system/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/QRD_Global_cal.acdb:system/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:system/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/msm8909-skut-snd-card/QRD_SKUT_Headset_cal.acdb:system/etc/acdbdata/QRD/msm8909-skut-snd-card/QRD_SKUT_Headset_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/msm8909-skut-snd-card/QRD_SKUT_Global_cal.acdb:system/etc/acdbdata/QRD/msm8909-skut-snd-card/QRD_SKUT_Global_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/msm8909-skut-snd-card/QRD_SKUT_General_cal.acdb:system/etc/acdbdata/QRD/msm8909-skut-snd-card/QRD_SKUT_General_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/msm8909-skut-snd-card/QRD_SKUT_Hdmi_cal.acdb:system/etc/acdbdata/QRD/msm8909-skut-snd-card/QRD_SKUT_Hdmi_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/msm8909-skut-snd-card/QRD_SKUT_Handset_cal.acdb:system/etc/acdbdata/QRD/msm8909-skut-snd-card/QRD_SKUT_Handset_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/msm8909-skut-snd-card/QRD_SKUT_Speaker_cal.acdb:system/etc/acdbdata/QRD/msm8909-skut-snd-card/QRD_SKUT_Speaker_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/msm8909-skut-snd-card/QRD_SKUT_Bluetooth_cal.acdb:system/etc/acdbdata/QRD/msm8909-skut-snd-card/QRD_SKUT_Bluetooth_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/QRD_Handset_cal.acdb:system/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:system/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/QRD_General_cal.acdb:system/etc/acdbdata/QRD/QRD_General_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/msm8909-skue-snd-card/QRD_SKUE_Headset_cal.acdb:system/etc/acdbdata/QRD/msm8909-skue-snd-card/QRD_SKUE_Headset_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/msm8909-skue-snd-card/QRD_SKUE_General_cal.acdb:system/etc/acdbdata/QRD/msm8909-skue-snd-card/QRD_SKUE_General_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/msm8909-skue-snd-card/QRD_SKUE_Global_cal.acdb:system/etc/acdbdata/QRD/msm8909-skue-snd-card/QRD_SKUE_Global_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/msm8909-skue-snd-card/QRD_SKUE_Hdmi_cal.acdb:system/etc/acdbdata/QRD/msm8909-skue-snd-card/QRD_SKUE_Hdmi_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/msm8909-skue-snd-card/QRD_SKUE_Speaker_cal.acdb:system/etc/acdbdata/QRD/msm8909-skue-snd-card/QRD_SKUE_Speaker_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/msm8909-skue-snd-card/QRD_SKUE_Bluetooth_cal.acdb:system/etc/acdbdata/QRD/msm8909-skue-snd-card/QRD_SKUE_Bluetooth_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/QRD/msm8909-skue-snd-card/QRD_SKUE_Handset_cal.acdb:system/etc/acdbdata/QRD/msm8909-skue-snd-card/QRD_SKUE_Handset_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:system/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/MTP_Global_cal.acdb:system/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/MTP_General_cal.acdb:system/etc/acdbdata/MTP/MTP_General_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/MTP_Headset_cal.acdb:system/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:system/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:system/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/acdbdata/MTP/MTP_Handset_cal.acdb:system/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    $(LOCAL_PATH)/proprietary/etc/init.qti.synaptics_dsx_qhd.sh:system/etc/init.qti.synaptics_dsx_qhd.sh \
    $(LOCAL_PATH)/proprietary/etc/sec_config:system/etc/sec_config \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmparser_lite.so:system/vendor/lib/libmmparser_lite.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_sp2508_brodsands_ffln_78_preview.so:system/vendor/lib/libchromatix_sp2508_brodsands_ffln_78_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_hi545_qtech_baly_40.so:system/vendor/lib/libmmcamera_hi545_qtech_baly_40.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/lib-imsdpl.so:system/vendor/lib/lib-imsdpl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfduibcsrcinterface.so:system/vendor/lib/libwfduibcsrcinterface.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libcneconn.so:system/vendor/lib/libcneconn.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libbdpush_V2_5.so:system/vendor/lib/libbdpush_V2_5.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libextendedremotedisplay.so:system/vendor/lib/libextendedremotedisplay.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/liblowi_wifihal.so:system/vendor/lib/liblowi_wifihal.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_sunny_q13v04b_eeprom.so:system/vendor/lib/libmmcamera_sunny_q13v04b_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_common_ar0542_eeprom.so:system/vendor/lib/libmmcamera_common_ar0542_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/liblistenjni.so:system/vendor/lib/liblistenjni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so:system/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libtzplayready.so:system/vendor/lib/libtzplayready.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_hi545_ofilm_baly_40.so:system/vendor/lib/libmmcamera_hi545_ofilm_baly_40.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libasn1cper.so:system/vendor/lib/libasn1cper.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/drm/libomadrmengine.so:system/vendor/lib/drm/libomadrmengine.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/drm/libdrmprplugin.so:system/vendor/lib/drm/libdrmprplugin.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libril-qc-radioconfig.so:system/vendor/lib/libril-qc-radioconfig.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqct_resampler.so:system/vendor/lib/libqct_resampler.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/hw/keystore.msm8909.so:system/vendor/lib/hw/keystore.msm8909.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/hw/gatekeeper.msm8909.so:system/vendor/lib/hw/gatekeeper.msm8909.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/hw/sound_trigger.primary.msm8909.so:system/vendor/lib/hw/sound_trigger.primary.msm8909.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_truly_cm7700_eeprom.so:system/vendor/lib/libmmcamera_truly_cm7700_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_ad5820_8532bl1_ofilm_camera.so:system/vendor/lib/libactuator_ad5820_8532bl1_ofilm_camera.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_pdaf.so:system/vendor/lib/libmmcamera_pdaf.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsrsprocessing.so:system/vendor/lib/libsrsprocessing.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfdsm.so:system/vendor/lib/libwfdsm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfdhdcpcp.so:system/vendor/lib/libwfdhdcpcp.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdpmnsrm.so:system/vendor/lib/libdpmnsrm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_sysinfo.so:system/vendor/lib/mmi_sysinfo.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_wifi.so:system/vendor/lib/mmi_wifi.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsmwrapper.so:system/vendor/lib/libsmwrapper.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_camera.so:system/vendor/lib/mmi_camera.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libFileMux.so:system/vendor/lib/libFileMux.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/lib-imsqimf.so:system/vendor/lib/lib-imsqimf.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/lib-imscamera.so:system/vendor/lib/lib-imscamera.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libFidoCryptoJNI.so:system/vendor/lib/libFidoCryptoJNI.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libOmxMux.so:system/vendor/lib/libOmxMux.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfdnative.so:system/vendor/lib/libwfdnative.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_sunny_ov8858_q8v19w_eeprom.so:system/vendor/lib/libmmcamera_sunny_ov8858_q8v19w_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libprdrmdecrypt.so:system/vendor/lib/libprdrmdecrypt.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsubsystem_control.so:system/vendor/lib/libsubsystem_control.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/lib-rtpsl.so:system/vendor/lib/lib-rtpsl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_bluetooth.so:system/vendor/lib/mmi_bluetooth.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmipstreamaal.so:system/vendor/lib/libmmipstreamaal.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_hi545_ofilm_baly_40_default_video.so:system/vendor/lib/libchromatix_hi545_ofilm_baly_40_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_sensor.so:system/vendor/lib/mmi_sensor.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmwfdsrcinterface.so:system/vendor/lib/libmmwfdsrcinterface.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/lib-imsSDP.so:system/vendor/lib/lib-imsSDP.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/sensor_calibrate.so:system/vendor/lib/sensor_calibrate.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_key.so:system/vendor/lib/mmi_key.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_ad5820_8532bl1_qtech.so:system/vendor/lib/libactuator_ad5820_8532bl1_qtech.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libasn1crt.so:system/vendor/lib/libasn1crt.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmi.so:system/vendor/lib/libmmi.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so:system/vendor/lib/libmmcamera_ofilm_oty5f03_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libloc_xtra.so:system/vendor/lib/libloc_xtra.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_sunny_q5v22e_eeprom.so:system/vendor/lib/libmmcamera_sunny_q5v22e_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_hi545_qtech_baly_40_default_video.so:system/vendor/lib/libchromatix_hi545_qtech_baly_40_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_sunrise_pc0fe_eeprom.so:system/vendor/lib/libmmcamera_sunrise_pc0fe_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libts_detected_face_jni.so:system/vendor/lib/libts_detected_face_jni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdpmframework.so:system/vendor/lib/libdpmframework.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_hi545_ofilm_baly_40_snapshot.so:system/vendor/lib/libchromatix_hi545_ofilm_baly_40_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsregex.so:system/vendor/lib/libsregex.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/lib-rtpdaemoninterface.so:system/vendor/lib/lib-rtpdaemoninterface.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libgdtap.so:system/vendor/lib/libgdtap.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmipstreamnetwork.so:system/vendor/lib/libmmipstreamnetwork.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqcmaputils.so:system/vendor/lib/libqcmaputils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_sp2508_brodsands_ffln_78.so:system/vendor/lib/libmmcamera_sp2508_brodsands_ffln_78.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libconnctrl.so:system/vendor/lib/libconnctrl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmwfdinterface.so:system/vendor/lib/libmmwfdinterface.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libcalmodule_gyroscope.so:system/vendor/lib/libcalmodule_gyroscope.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwqe.so:system/vendor/lib/libwqe.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_fm.so:system/vendor/lib/mmi_fm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libFIDOKeyProvisioning.so:system/vendor/lib/libFIDOKeyProvisioning.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmcseng.so:system/vendor/lib/libmcseng.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libstlport_sta.so:system/vendor/lib/libstlport_sta.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_gc2355_huaquan_ffln_78_common.so:system/vendor/lib/libchromatix_gc2355_huaquan_ffln_78_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so:system/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libslimclient.so:system/vendor/lib/libslimclient.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/lib-imsrcscm.so:system/vendor/lib/lib-imsrcscm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmQSM.so:system/vendor/lib/libmmQSM.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libvcel.so:system/vendor/lib/libvcel.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_battery.so:system/vendor/lib/mmi_battery.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so:system/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/liblowi_wifihal_nl.so:system/vendor/lib/liblowi_wifihal_nl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libstaapi.so:system/vendor/lib/libstaapi.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_storage.so:system/vendor/lib/mmi_storage.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libalarmservice_jni.so:system/vendor/lib/libalarmservice_jni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/lib-rtpcore.so:system/vendor/lib/lib-rtpcore.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_speaker.so:system/vendor/lib/mmi_speaker.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_sunny_q5v41b_eeprom.so:system/vendor/lib/libmmcamera_sunny_q5v41b_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_ad5820_8532bl1_ofilm_camcorder.so:system/vendor/lib/libactuator_ad5820_8532bl1_ofilm_camcorder.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/soundfx/libswdap.so:system/vendor/lib/soundfx/libswdap.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_gc2355_huaquan_ffln_78_default_video.so:system/vendor/lib/libchromatix_gc2355_huaquan_ffln_78_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_sonyimx135_eeprom.so:system/vendor/lib/libmmcamera_sonyimx135_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/lib-rtpcommon.so:system/vendor/lib/lib-rtpcommon.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libChamomilePA.so:system/vendor/lib/libChamomilePA.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libavenhancements.so:system/vendor/lib/libavenhancements.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libacdbmapper.so:system/vendor/lib/libacdbmapper.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libasn1crtx.so:system/vendor/lib/libasn1crtx.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmrtpdecoder.so:system/vendor/lib/libmmrtpdecoder.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libtzdrmgenprov.so:system/vendor/lib/libtzdrmgenprov.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdpmfdmgr.so:system/vendor/lib/libdpmfdmgr.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_hi545_ofilm_baly_40_common.so:system/vendor/lib/libchromatix_hi545_ofilm_baly_40_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmrtpencoder.so:system/vendor/lib/libmmrtpencoder.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libSecureSampleAuthJNI.so:system/vendor/lib/libSecureSampleAuthJNI.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_touch.so:system/vendor/lib/mmi_touch.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_lcd.so:system/vendor/lib/mmi_lcd.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdpmctmgr.so:system/vendor/lib/libdpmctmgr.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libvoice-svc.so:system/vendor/lib/libvoice-svc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_pdafcamif.so:system/vendor/lib/libmmcamera_pdafcamif.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmwfdsinkinterface.so:system/vendor/lib/libmmwfdsinkinterface.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfdmmsrc.so:system/vendor/lib/libwfdmmsrc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmm-hdcpmgr.so:system/vendor/lib/libmm-hdcpmgr.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmhttpstack.so:system/vendor/lib/libmmhttpstack.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_ad5820_8532bl1_ofilm.so:system/vendor/lib/libactuator_ad5820_8532bl1_ofilm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/lib-rcsjni.so:system/vendor/lib/lib-rcsjni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libnative_audio_latency_jni.so:system/vendor/lib/libnative_audio_latency_jni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/lib-imsrcscmservice.so:system/vendor/lib/lib-imsrcscmservice.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdlbdapstorage.so:system/vendor/lib/libdlbdapstorage.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/lib-imss.so:system/vendor/lib/lib-imss.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqti-at.so:system/vendor/lib/libqti-at.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdme_main.so:system/vendor/lib/libdme_main.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libcne.so:system/vendor/lib/libcne.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsta_lib_third_party_libsta_lib_libsta_gyp.so:system/vendor/lib/libsta_lib_third_party_libsta_lib_libsta_gyp.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_headset.so:system/vendor/lib/mmi_headset.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_gc2355_huaquan_ffln_78.so:system/vendor/lib/libmmcamera_gc2355_huaquan_ffln_78.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/liblocationservice_glue.so:system/vendor/lib/liblocationservice_glue.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_hi545_ofilm_baly_40_full_video.so:system/vendor/lib/libchromatix_hi545_ofilm_baly_40_full_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/lib-imsvt.so:system/vendor/lib/lib-imsvt.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfdservice.so:system/vendor/lib/libwfdservice.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libhwdaphal.so:system/vendor/lib/libhwdaphal.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsta_lib_third_party_staproxy_sta_proxy_loader_gyp.so:system/vendor/lib/libsta_lib_third_party_staproxy_sta_proxy_loader_gyp.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_hi545_qtech_baly_40_common.so:system/vendor/lib/libchromatix_hi545_qtech_baly_40_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libaudioalsa.so:system/vendor/lib/libaudioalsa.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_hi545_qtech_baly_40_preview.so:system/vendor/lib/libchromatix_hi545_qtech_baly_40_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libcalmodule_common.so:system/vendor/lib/libcalmodule_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmm-qdcm.so:system/vendor/lib/libmm-qdcm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmm-disp-apis.so:system/vendor/lib/libmm-disp-apis.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfdrtsp.so:system/vendor/lib/libwfdrtsp.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libFlacSwDec.so:system/vendor/lib/libFlacSwDec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmipstreamutils.so:system/vendor/lib/libmmipstreamutils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmdsprpc.so:system/vendor/lib/libmdsprpc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libNimsWrap.so:system/vendor/lib/libNimsWrap.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libFidoCrypto.so:system/vendor/lib/libFidoCrypto.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_sp2508_brodsands_ffln_78_default_video.so:system/vendor/lib/libchromatix_sp2508_brodsands_ffln_78_default_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libscve.so:system/vendor/lib/libscve.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_gc2355_huaquan_ffln_78_snapshot.so:system/vendor/lib/libchromatix_gc2355_huaquan_ffln_78_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_hi545_qtech_baly_40_snapshot.so:system/vendor/lib/libchromatix_hi545_qtech_baly_40_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libstagefright_soft_ddpdec.so:system/vendor/lib/libstagefright_soft_ddpdec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/lib-imsrcs.so:system/vendor/lib/lib-imsrcs.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfdcommonutils.so:system/vendor/lib/libwfdcommonutils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_sp2508_brodsands_ffln_78_snapshot.so:system/vendor/lib/libchromatix_sp2508_brodsands_ffln_78_snapshot.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/lib-dplmedia.so:system/vendor/lib/lib-dplmedia.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libloc_ext.so:system/vendor/lib/libloc_ext.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfdmmsink.so:system/vendor/lib/libwfdmmsink.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libSampleAuthJNI.so:system/vendor/lib/libSampleAuthJNI.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_sunny_q13v06k_eeprom.so:system/vendor/lib/libmmcamera_sunny_q13v06k_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_headset_loop.so:system/vendor/lib/mmi_headset_loop.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libvendorconn.so:system/vendor/lib/libvendorconn.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_q3a_core.so:system/vendor/lib/libmmcamera2_q3a_core.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_gc2355_huaquan_ffln_78_preview.so:system/vendor/lib/libchromatix_gc2355_huaquan_ffln_78_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libCommandSvc.so:system/vendor/lib/libCommandSvc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/lib-rcsimssjni.so:system/vendor/lib/lib-rcsimssjni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfduibcsinkinterface.so:system/vendor/lib/libwfduibcsinkinterface.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libSecureSampleAuthClient.so:system/vendor/lib/libSecureSampleAuthClient.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_ad5820_8532bl1_qtech_camcorder.so:system/vendor/lib/libactuator_ad5820_8532bl1_qtech_camcorder.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libactuator_ad5820_8532bl1_qtech_camera.so:system/vendor/lib/libactuator_ad5820_8532bl1_qtech_camera.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libxt_native.so:system/vendor/lib/libxt_native.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libjnihelper.so:system/vendor/lib/libjnihelper.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_sim.so:system/vendor/lib/mmi_sim.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libcneqmiutils.so:system/vendor/lib/libcneqmiutils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/liblqe.so:system/vendor/lib/liblqe.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_hi545_ofilm_baly_40_preview.so:system/vendor/lib/libchromatix_hi545_ofilm_baly_40_preview.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libts_face_beautify_jni.so:system/vendor/lib/libts_face_beautify_jni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/lib-imsrcscmclient.so:system/vendor/lib/lib-imsrcscmclient.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfduibcsink.so:system/vendor/lib/libwfduibcsink.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_nfc.so:system/vendor/lib/mmi_nfc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libOmxIttiamVdec.so:system/vendor/lib/libOmxIttiamVdec.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_hi545_qtech_baly_40_full_video.so:system/vendor/lib/libchromatix_hi545_qtech_baly_40_full_video.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/lib-imsxml.so:system/vendor/lib/lib-imsxml.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/lib-ims-rcscmjni.so:system/vendor/lib/lib-ims-rcscmjni.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfduibcinterface.so:system/vendor/lib/libwfduibcinterface.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libQtiTether.so:system/vendor/lib/libQtiTether.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_vibrator.so:system/vendor/lib/mmi_vibrator.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_memory.so:system/vendor/lib/mmi_memory.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libSubSystemShutdown.so:system/vendor/lib/libSubSystemShutdown.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfdmmutils.so:system/vendor/lib/libwfdmmutils.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdpmtcm.so:system/vendor/lib/libdpmtcm.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libtar.so:system/vendor/lib/libtar.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_hall.so:system/vendor/lib/mmi_hall.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libdataitems.so:system/vendor/lib/libdataitems.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_flashlight.so:system/vendor/lib/mmi_flashlight.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libchromatix_sp2508_brodsands_ffln_78_common.so:system/vendor/lib/libchromatix_sp2508_brodsands_ffln_78_common.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmiipstreammmihttp.so:system/vendor/lib/libmmiipstreammmihttp.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libscve_mv.so:system/vendor/lib/libscve_mv.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_handset_loop.so:system/vendor/lib/mmi_handset_loop.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwms.so:system/vendor/lib/libwms.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_cpu.so:system/vendor/lib/mmi_cpu.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libMpeg4SwEncoder.so:system/vendor/lib/libMpeg4SwEncoder.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_dw9761b_eeprom.so:system/vendor/lib/libmmcamera_dw9761b_eeprom.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmipstreamsourcehttp.so:system/vendor/lib/libmmipstreamsourcehttp.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmm-als.so:system/vendor/lib/libmm-als.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libwfduibcsrc.so:system/vendor/lib/libwfduibcsrc.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/liblistensoundmodel2.so:system/vendor/lib/liblistensoundmodel2.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_audio.so:system/vendor/lib/mmi_audio.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mediadrm/libprmediadrmplugin.so:system/vendor/lib/mediadrm/libprmediadrmplugin.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mediadrm/libprmediadrmdecrypt.so:system/vendor/lib/mediadrm/libprmediadrmdecrypt.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_light.so:system/vendor/lib/mmi_light.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    $(LOCAL_PATH)/proprietary/vendor/lib/mmi_gps.so:system/vendor/lib/mmi_gps.so \
    $(LOCAL_PATH)/proprietary/vendor/etc/calmodule.cfg:system/vendor/etc/calmodule.cfg \
    $(LOCAL_PATH)/proprietary/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine \
    $(LOCAL_PATH)/proprietary/vendor/bin/fidodaemon:system/vendor/bin/fidodaemon \
    $(LOCAL_PATH)/proprietary/vendor/bin/perfd:system/vendor/bin/perfd \
    $(LOCAL_PATH)/proprietary/vendor/bin/sampleauthdaemon:system/vendor/bin/sampleauthdaemon \
    $(LOCAL_PATH)/proprietary/vendor/bin/audioflacapp:system/vendor/bin/audioflacapp \
    $(LOCAL_PATH)/proprietary/vendor/bin/slim_daemon:system/vendor/bin/slim_daemon \
    $(LOCAL_PATH)/proprietary/vendor/bin/chamomile_provision:system/vendor/bin/chamomile_provision \
    $(LOCAL_PATH)/proprietary/vendor/bin/qti:system/vendor/bin/qti \
    $(LOCAL_PATH)/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    $(LOCAL_PATH)/proprietary/bin/pm-service:system/bin/pm-service \
    $(LOCAL_PATH)/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    $(LOCAL_PATH)/proprietary/bin/setproperties:system/bin/setproperties \
    $(LOCAL_PATH)/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    $(LOCAL_PATH)/proprietary/bin/irsc_util:system/bin/irsc_util \
    $(LOCAL_PATH)/proprietary/bin/rild:system/bin/rild \
    $(LOCAL_PATH)/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    $(LOCAL_PATH)/proprietary/bin/wcnss_service:system/bin/wcnss_service \
    $(LOCAL_PATH)/proprietary/bin/perf:system/bin/perf \
    $(LOCAL_PATH)/proprietary/bin/btnvtool:system/bin/btnvtool \
    $(LOCAL_PATH)/proprietary/bin/cnss-daemon:system/bin/cnss-daemon \
    $(LOCAL_PATH)/proprietary/bin/qcom-system-daemon:system/bin/qcom-system-daemon \
    $(LOCAL_PATH)/proprietary/bin/mm-audio-ftm:system/bin/mm-audio-ftm \
    $(LOCAL_PATH)/proprietary/bin/qseecom_sample_client:system/bin/qseecom_sample_client \
    $(LOCAL_PATH)/proprietary/bin/serialno:system/bin/serialno \
    $(LOCAL_PATH)/proprietary/bin/qseecomd:system/bin/qseecomd
